# Generated by Django 6.0 on 2026-01-13 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0003_alter_event_moderators_alter_event_news_and_more"),
        ("news_app", "0002_alter_news_author"),
        ("role_app", "0003_alter_roleinevent_user"),
        ("users_app", "0002_remove_customuser_job_remove_customuser_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
