# Generated by Django 6.0 on 2026-01-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("role_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roleinevent",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
