# Generated by Django 6.0 on 2026-01-14 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0002_event_news"),
        ("role_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roleinevent",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="calendar_app.event",
            ),
        ),
    ]
