# Generated by Django 6.0 on 2026-01-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("role_app", "0002_alter_roleinevent_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roleinevent",
            name="approved",
        ),
    ]
