# Generated by Django 6.0 on 2026-01-13 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("role_app", "0002_roleinevent_approved"),
        ("users_app", "0002_remove_customuser_job_remove_customuser_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roleinevent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roles",
                to="users_app.userprofile",
            ),
        ),
    ]
