# Generated by Django 6.0 on 2026-01-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("role_app", "0004_roleinevent_unique_role"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="roleinevent",
            name="unique_role",
        ),
    ]
