# Generated by Django 6.0 on 2026-01-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0002_event_news"),
        ("role_app", "0005_remove_roleinevent_unique_role"),
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="roleinevent",
            constraint=models.UniqueConstraint(
                fields=("role", "user", "event"), name="unique_role"
            ),
        ),
    ]
