# Generated by Django 6.0 on 2026-01-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0001_initial"),
        ("news_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="news",
            field=models.ManyToManyField(
                blank=True, related_name="event_news", to="news_app.news"
            ),
        ),
    ]
