# Generated by Django 6.0 on 2026-01-13 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0002_initial"),
        ("news_app", "0002_alter_news_author"),
        ("users_app", "0002_remove_customuser_job_remove_customuser_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="moderators",
            field=models.ManyToManyField(
                related_name="event_moderators", to="users_app.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="news",
            field=models.ManyToManyField(
                blank=True, related_name="event_news", to="news_app.news"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="users_app.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                related_name="event_participants", to="users_app.userprofile"
            ),
        ),
    ]
