# Generated by Django 6.0 on 2026-01-14 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calendar_app", "0002_event_news"),
        ("role_app", "0001_initial"),
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_date", models.DateField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_app.event",
                    ),
                ),
                (
                    "requested_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="role_app.role"
                    ),
                ),
                (
                    "user_requested",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users_app.userprofile",
                    ),
                ),
            ],
        ),
    ]
