# Generated by Django 6.0 on 2026-01-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="requests",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
