# Generated by Django 6.0 on 2026-01-14 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings_app", "0002_requests_status"),
        ("role_app", "0003_remove_roleinevent_approved"),
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requests",
            name="requested_role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requested_role",
                to="role_app.role",
            ),
        ),
        migrations.AlterField(
            model_name="requests",
            name="user_requested",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="users_app.userprofile",
            ),
        ),
    ]
