# Generated by Django 6.0 on 2026-01-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0002_event_news"),
        ("mailings_app", "0003_alter_requests_requested_role_and_more"),
        ("role_app", "0003_remove_roleinevent_approved"),
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="requests",
            constraint=models.UniqueConstraint(
                fields=("event", "user_requested", "requested_role"),
                name="unique_request",
            ),
        ),
    ]
