# Generated by Django 6.0 on 2026-01-06 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calendar_app", "0001_initial"),
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("information", models.TextField()),
                ("published_date", models.DateField()),
                (
                    "author",
                    models.ForeignKey(
                        default=1,
                        max_length=100,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users_app.customuser",
                    ),
                ),
                (
                    "connected_events",
                    models.ManyToManyField(
                        blank=True,
                        related_name="news_connected_events",
                        to="calendar_app.event",
                    ),
                ),
            ],
        ),
    ]
