# Generated by Django 6.0 on 2026-01-13 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_app", "0001_initial"),
        ("users_app", "0002_remove_customuser_job_remove_customuser_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="author",
            field=models.ForeignKey(
                default=1,
                max_length=100,
                on_delete=django.db.models.deletion.PROTECT,
                to="users_app.userprofile",
            ),
        ),
    ]
